eye/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^result', views.result, name = 'result'),
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^eye/', include(('eye.urls', 'eye'), namespace='eye'))
]

eye/models.py
from django.db import models

class Picture(models.Model):
    images = models.CharField(max_length = 200)

eye/views.py
from django.http import HttpResponse
from .models import Picture
from django.template import loader
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage


def index(request):
	return render(request, 'eye/index.html', {})

def result(request):
    if request.method == 'POST' and request.FILES['eyeimage']:

        import os
        PROJECT_PATH = os.path.abspath(os.path.dirname(__file__))
        CAPTHA_ROOT = os.path.join(PROJECT_PATH,'test_images','uploaded','uploaded.jpg')
        os.remove(CAPTHA_ROOT)

        myfile = request.FILES['eyeimage']
        fs = FileSystemStorage()
        filename = fs.save('uploaded.jpg', myfile)
        uploaded_file_url = fs.url(filename)

        uploaded_file_url = os.path.join(PROJECT_PATH,'test_images', 'uploaded', 'uploaded.jpg')

        from .classifier import prediction
        tested, percent = prediction()

        return render(request, 'eye/results.html', {
            'tested': tested, 'percent' : percent, 'uploaded_file_url' : uploaded_file_url
        })


    return render(request, 'eye/results.html')

eye/templates/eye/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Retinanalyzer</title>
	<meta name="description" content="Retinanalyzer" />
	<meta name="msapplication-TileColor" content="#00a8ff">
	<meta name="msapplication-config" content="img/favicons/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">
	<!-- Normalize -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
	<!-- Bootstrap -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<!-- Owl -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.css' %}">
	<!-- Animate.css -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.1.0/css/font-awesome.min.css' %}">
	<!-- Elegant Icons -->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/eleganticons/et-icons.css' %}">
	<!-- Main style -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/cardio.css' %}">
</head>

<body style="overflow:hidden">
	<div class="preloader">
		<img src="{% static 'img/loader.gif' %}" alt="Preloader image">
	</div>
	<nav class="navbar">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}" data-active-url="{% static 'img/logo-active.png' %}" alt=""></a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right main-nav">
					<li style="margin-left:50px;margin-right:50px"></li>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container-fluid -->
	</nav>
	<header id="intro">
		<div class="container">
			<div class="table">
				<div class="header-text">
					<div class="row">
						<div class="col-md-12 text-center">
							<h3 class="light white">We only accept CSV file</h3>
							<h1 class="white typed" style="font-size:30px">Upload the document to be scanned</h1>
							<span class="typed-cursor">|</span>
                            <br/><br/><br/>
                            <a href="#" data-toggle="modal" data-target="#modal1" class="btn btn-blue">Upload the Scan</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content modal-popup">
				<a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
				<h3 class="white">Upload Image</h3>
				<form action="{% url 'eye:result' %}" class="popup-form" method="post" enctype="multipart/form-data">{% csrf_token %}
					<input type="file" class="form-control form-white" placeholder="Full Name" name="eyeimage">
					<button type="submit" class="btn btn-submit">Submit</button>
				</form>
			</div>
		</div>
	</div>
	<!-- Scripts -->
	<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script src="{% static 'js/typewriter.js' %}"></script>
	<script src="{% static 'js/jquery.onepagenav.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

eye/templates/eye/indexed.html
<h1>try me</h1>

<p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>

eye/templates/eye/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Retinanalyzer</title>
	<meta name="description" content="Retinanalyzer" />
	<meta name="msapplication-TileColor" content="#00a8ff">
	<meta name="msapplication-config" content="img/favicons/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">
	<!-- Normalize -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
	<!-- Bootstrap -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<!-- Owl -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.css' %}">
	<!-- Animate.css -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.1.0/css/font-awesome.min.css' %}">
	<!-- Elegant Icons -->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/eleganticons/et-icons.css' %}">
	<!-- Main style -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/cardio.css' %}">
</head>

<body style="overflow:hidden">
	<div class="preloader">
		<img src="{% static 'img/loader.gif' %}" alt="Preloader image">
	</div>
	<nav class="navbar">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}" data-active-url="{% static 'img/logo-active.png' %}" alt=""></a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right main-nav">
					<li style="margin-left:50px;margin-right:50px"></li>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container-fluid -->
	</nav>
	<header id="intro">
		<div class="container">
			<div class="table">
				<div class="header-text">
					<div class="row">
						<div class="col-md-12 text-center">
                            {% if tested %}
                            <!--img src="{% static '/uploaded/uploaded.jpg' %}">
                            <p>{{uploaded_file_url}}</p-->
							<h3 class="light white">The patient is diagnosed with Diabetic Retinopathy with a confidence of {{percent}}.</h3>
							<h1 class="white typed" style="font-size:30px">You need to take medical advice from a doctor.</h1>
							<span class="typed-cursor">|</span>
                            {% else %}
                            <h3 class="light white">No Issues Detected.</h3>
							<h1 class="white typed" style="font-size:30px">Your eyes are totaly fine.</h1>
							<span class="typed-cursor">|</span>
                            {% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- Scripts -->
	<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script src="{% static 'js/typewriter.js' %}"></script>
	<script src="{% static 'js/jquery.onepagenav.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>

</html>